# Numpy Basics
1. Creating Arrays
2. Array of Zeros and Ones
3. Range of Numbers
4. Reshaping Arrays
5. Basic Operations (Add, subtract, multiply, divide)
6. Array Statistics
7. Indexing and Slicing
8. Random Numbers
9. Identity Matrix
10. Flatten
11. Transpose
12. Concatenate
13. Unique
14. Sum along axis


In [48]:
import numpy as np

In [49]:
arr = np.array([1 , 2 ,3 ])
arr

TypeError: 'list' object is not callable

In [ ]:
arr1 = np.array=([[1 , 2 ,3] , [4 ,5 ,6]])
arr1

[[1, 2, 3], [4, 5, 6]]

In [ ]:
zero_arr = np.zeros(8)
one_arr = np.ones(4)
print(zero_arr)
one_arr

[0. 0. 0. 0. 0. 0. 0. 0.]


array([1., 1., 1., 1.])

In [ ]:
range_arr =  np.arange(8)
range_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
reshap1 = np.arange(9)
reshap1 = reshap1.reshape(3 , 3)
reshap1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
sample_arr = [8 , 9 ,10 , 11 , 12 , 13 , 14]
sample_arr2 = [ 1 , 2, 3 , 4 ,5 ,6 ,7]
print(sample_arr , sample_arr2)

plus = np.multiply(sample_arr , sample_arr2)
print(plus)

[8, 9, 10, 11, 12, 13, 14] [1, 2, 3, 4, 5, 6, 7]
[ 8 18 30 44 60 78 98]


In [ ]:
stat = [8 , 9 ,10 , 11 , 12 , 13 , 14]
print(np.sum(stat))
print(np.min(stat))
print(np.max(stat))
print(np.mean(stat))

77
8
14
11.0


In [ ]:
indexing = [8 , 9 ,10 , 11 , 12 , 13 , 14]
print(indexing[0:3])

[8, 9, 10]


In [ ]:
random = np.random.rand(4) + 2
for i in random:
    print(i)

2.933902229457387
2.623068146383437
2.17947987426419
2.4973686731030322


In [ ]:
iden = np.eye(4)
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])