In [2]:
import numpy as np

## Populate arrays with specific numbers

Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [3]:
one_dimensional_array = np.array(["abc" , 2 , 3 ,4 ,5])
one_dimensional_array

array(['abc', '2', '3', '4', '5'], dtype='<U11')

In [4]:
hetro_array = np.array([1 ,2 ,3 , 1.5])
hetro_array

array([1. , 2. , 3. , 1.5])

You can also use `np.array` to create a two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [5]:
two_dimensional_array = np.array([[1 , 2] , [3 , 4] , [5 , 6]])
two_dimensional_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
zeroes = np.zeros(5, dtype=int)
zeroes

array([0, 0, 0, 0, 0])

In [7]:
ones = np.ones(10 , dtype=int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [8]:
sequence = np.arange( 5 , 20)
sequence

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100. 




In [9]:
random_number = np.random.randint(low = 50 , high = 101 , size=(6,))
random_number

array([ 71,  56,  93, 100,  91,  97])

In [10]:
random_floats= np.random.random((6,))
random_floats

array([0.36148591, 0.5039309 , 0.26607144, 0.43062768, 0.1323317 ,
       0.33059182])

## Mathematical Operations on NumPy Operands


In [11]:
random_number_between_2_3 = random_floats + 2.0
random_number_between_2_3

array([2.36148591, 2.5039309 , 2.26607144, 2.43062768, 2.1323317 ,
       2.33059182])

In [12]:
random_number_between_150_300 = random_number * 3
random_number_between_150_300

array([213, 168, 279, 300, 273, 291])

# Creating List with Mixed Data Types

In [13]:
arr = [1 , 2.5 , "Arham" , {"key" : "vales"} , 1]
mixed = np.array(arr)
arr

[1, 2.5, 'Arham', {'key': 'vales'}, 1]