In [46]:
import numpy as np

## Populate arrays with specific numbers

Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [47]:
one_dimensional_array = np.array(["abc" , 2 , 3 ,4 ,5])
one_dimensional_array

array(['abc', '2', '3', '4', '5'], dtype='<U11')

In [48]:
hetro_array = np.array([1 ,2 ,3 , 1.5])
hetro_array

array([1. , 2. , 3. , 1.5])

You can also use `np.array` to create a two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [49]:
two_dimensional_array = np.array([[1 , 2] , [3 , 4] , [5 , 6]])
two_dimensional_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
zeroes = np.zeros(5, dtype=int)
zeroes

array([0, 0, 0, 0, 0])

In [51]:
ones = np.ones(10 , dtype=int)
ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [52]:
sequence = np.arange( 5 , 20)
sequence

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100. 




In [53]:
random_number = np.random.randint(low = 50 , high = 101 , size=(6,))
random_number

array([100,  70,  99,  96,  70,  54])

In [54]:
random_floats= np.random.random((6,))
random_floats

array([0.88706044, 0.37323357, 0.99043498, 0.5074777 , 0.63871225,
       0.45111192])

## Mathematical Operations on NumPy Operands


In [55]:
random_number_between_2_3 = random_floats + 2.0
random_number_between_2_3

array([2.88706044, 2.37323357, 2.99043498, 2.5074777 , 2.63871225,
       2.45111192])

In [56]:
random_number_between_150_300 = random_number * 3
random_number_between_150_300

array([300, 210, 297, 288, 210, 162])

# Creating List with Mixed Data Types

In [58]:
arr = [1 , 2.5 , "Arham" , {"key" : "vales"} , 1]
mixed = np.array(arr)
mixed

array([1, 2.5, 'Arham', {'key': 'vales'}, 1], dtype=object)